# Site settings
title: Adab1ts - Desenvolupament web, programari lliure i consultoria tecnològica
brand: Adab1ts
description: Tecnologia al servei de les persones. Desenvolupament web, programari lliure i consultoria tecnològica.
baseurl: ''
url: http://www.adabits.org
email: info@adabits.org

# Where things are
source: .
destination: ./_site
plugins_dir: _plugins
layouts_dir: _layouts
data_dir: _data
includes_dir: _includes

# Paths
# sass:
#   sass_dir: assets/styles

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 00804c
  primary-rgb: [0, 128, 76]
  secondary: b50033
  secondary-dark: 910029

# Collections
collections:
  - benefits
  - principles
  - services
  - projects

# Team names, titles and social links
people:
- name: Klaudia Álvarez
  pic: 1
  position: Lead Designer
  bio: Llicenciada en Comunicació audiovisual. Màster en Art i Educació. Web designer. Gestora cultural. A mig camí entre les belles arts, la pedagogia i la comunicació 2.0. Entusiasta de la fotografia analògica i defensora de la cultura lliure. Compagino la meva feina a Adab1ts amb l'activisme en comunicació i l’escriptura de la meva tesi doctoral.
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/klaudiaalvarez

- name: Carles Muiños
  pic: 2
  position: Lead Developer
  bio: Enginyer informàtic. Màster en Software Lliure. Full Stack web developer i administrador de sistemes GNU/Linux. Faig acompanyament en l'aprenentatge d'eines lliures com a contribució a l'alfabetització digital de la ciutadania. Allibero màquines, codi i coneixement.
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/carles-muinos
    - title: github
      url: https://github.com/zuzust

- name: Ada Lovelace
  pic: 3
  position: Enchantress of Numbers
  bio: |
    Nascuda al 1815, se la considera la inventora del primer llenguatge de programació de propòsit general. La seva figura és un símbol per les dones en un sector tan masculinitzat com el de la tecnologia.
    Per nosaltres Ada Lovelace és una font d’inspiració a la qual homenatgem amb el nostre nom i el disseny del nostre logo, en referència a la flor que Ada portava al cap en el més famós dels seus retrats.
  social:
    - title: wikipedia-w
      url: https://ca.wikipedia.org/wiki/Ada_Lovelace

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/adab1ts
  - title: facebook
    url: https://www.facebook.com/Adab1ts
  - title: linkedin
    url: https://www.linkedin.com/company/adab1ts
  - title: github
    url: https://github.com/adab1ts
  - title: envelope
    url: mailto:info@adabits.org
  - title: map-marker
    url: https://goo.gl/maps/dszLw7eXLyM2




# Handling Reading
exclude: ["LICENSE.md", "README.md", "Gemfile", "Gemfile.lock", "mail"]
# Handling Reading
encoding: "utf-8"
markdown_ext: "md"

# Filtering Content
show_drafts: false
future:      false

# Plugins
gems:
#   - jekyll-redirect-from
#- jekyll-sitemap
- jekyll-feed


theme: agency-jekyll-theme

# Conversion
markdown:    kramdown
highlighter: rouge

# Outputting
timezone: Europe/Madrid
permalink: pretty

# Markdown Processors
kramdown:
  input: GFM
