# Site settings
title: Adab1ts - Desenvolupament web, programari lliure i consultoria tecnològica
brand: Adab1ts
description: Tecnologia al servei de les persones. Desenvolupament web, programari lliure i consultoria tecnològica.
baseurl: ''
url: http://www.adabits.org
email: info@adabits.org

# Where things are
source: .
destination: ./_site
plugins_dir: _plugins
layouts_dir: _layouts
data_dir: _data
includes_dir: _includes

# Paths
# sass:
#   sass_dir: assets/styles

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 00804c
  primary-rgb: [0, 128, 76]
  secondary: b50033
  secondary-dark: 910029

# Collections
collections:
  - benefits
  - principles
  - projects


# Handling Reading
exclude: ["LICENSE.md", "README.md", "Gemfile", "Gemfile.lock", "mail"]
# Handling Reading
encoding: "utf-8"
markdown_ext: "md"

# Filtering Content
show_drafts: false
future:      false

# Plugins
gems:
#   - jekyll-redirect-from
#- jekyll-sitemap
- jekyll-feed


theme: agency-jekyll-theme

# Conversion
markdown:    kramdown
highlighter: rouge

# Outputting
timezone: Europe/Madrid
permalink: pretty

# Markdown Processors
kramdown:
  input: GFM
