- name: "Desenvolupament web i mòbil"
  icon: "code"
  description:
    - "Desenvolupament d’aplicacions web a mida."
    - "Mobile Apps."
    - "Gestors de continguts."
    - "Botigues online."
    - "Web estàtica moderna."
    - "Landing pages i webs promocionals."
    - "Disseny de correu HTML."
    - "Serveis associats: SEO, certificats SSL."
    - "Formació específica."


- name: "Implantació de programari lliure"
  icon: "linux"
  description:
    - "Implantació de sistemes operatius i programari lliure."
    - "Integració de solucions de programari lliure per entorns corporatius: CRM, ERP, productivitat en el Núvol, …"
    - "Formació i acompanyament en l’adaptació al nou entorn."

- name: "Consultoria tecnològica"
  icon: "comments"
  description:
    - "Optimització d’infraestructura."
    - "Seguretat en les comunicacions i protecció de la informació."
    - "Treball en xarxa i gestió compartida de projectes."
    - "Gestió documental."
    - "Eines de gestió econòmica i de clients."
    - "Comunicació interna."
    - "Foment de la participació i presa de decisions col·lectiva."
